version: '3.9'

services:

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - php

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    restart: unless-stopped