FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libwebp-dev \
    libjpeg-dev

RUN docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip pdo_mysql

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY composer.json /var/www/composer.json

RUN composer install --no-autoloader --no-dev --prefer-dist -vvv

COPY ./giorgioreale.xyz /var/www/giorgioreale.xyz
COPY ./cv.giorgioreale.xyz /var/www/cv.giorgioreale.xyz

COPY data.json /var/www/giorgioreale.xyz/public/data.json
COPY data.json /var/www/cv.giorgioreale.xyz/public/data.json

RUN composer dump-autoload --no-dev --optimize

RUN cp -r vendor/ giorgioreale.xyz/public/controllers
RUN cp -r vendor/ cv.giorgioreale.xyz/public/controllers

EXPOSE 9000
CMD ["php-fpm"]
